disable_existing_loggers: false
formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
  file:
    backupCount: 5
    class: logging.handlers.RotatingFileHandler
    filename: logs/nfc_relay.log
    formatter: detailed
    level: DEBUG
    maxBytes: 10485760
loggers:
  ? ''
  : handlers:
    - console
    - file
    level: DEBUG
    propagate: false
version: 1
